project_id = "byvazfrvoanojfayvsaz"

[functions.create-crm-user]
verify_jwt = false

[functions.dfw-webhook-trigger]
verify_jwt = false

[functions.send-lead-webhook]
verify_jwt = false

[functions.send-giveaway-email]
verify_jwt = false

[functions.visualize-floor]
verify_jwt = false