project_id = "byvazfrvoanojfayvsaz"

[functions.create-crm-user]
verify_jwt = false

[functions.deactivate-user]
verify_jwt = false

[functions.reactivate-user]
verify_jwt = false

[functions.dfw-webhook-trigger]
verify_jwt = false

[functions.send-lead-webhook]
verify_jwt = false

[functions.send-giveaway-email]
verify_jwt = false

[functions.visualize-floor]
verify_jwt = false

[functions.send-quote-webhook]
verify_jwt = false

[functions.send-floor-packet-webhook]
verify_jwt = false

[functions.jobber-api]
verify_jwt = false

[functions.jobber-oauth-callback]
verify_jwt = false
[functions.sitemap]
verify_jwt = false
