// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://byvazfrvoanojfayvsaz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ5dmF6ZnJ2b2Fub2pmYXl2c2F6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjQ4ODAsImV4cCI6MjA2NTUwMDg4MH0._UYJK6diQbMMlh-_uhDtgiyBq_Ama6Qd-NYQkugbfHc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);